handlers=java.util.logging.ConsoleHandler
.level=INFO

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%4$s: %5$s%n

# Completely suppress Natty parser and related library logging
com.joestelmach.level=SEVERE
com.joestelmach.natty.level=SEVERE
net.objectlab.level=SEVERE
org.antlr.level=SEVERE
# Also silence Quartz scheduler
org.quartz.level=SEVERE
